spring:
  datasource:
    url: jdbc:postgresql://localhost:5001/postgres
    username: postgres
    password: root

  application:
    name: authorization-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9002

grpc:
  server:
    port: 9001

logging:
  level:
    org:
      springframework:
        security: trace

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
