server:
  port: 6001

spring:

  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5001/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 7001
  client:
    authorization-service:
      address: "discovery:///authorization-service"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

logging:
  level:
    org:
      springframework:
        security: trace
