server:
  port: 6003

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000


  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5003/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 7003

  client:
    cart-service:
      address: "discovery:///cart-service"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

