server:
  port: 6004

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000


  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5004/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 7004
