server:
  port: 6004

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5004/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
  elasticsearch:
    uri: 'http://localhost:9200'


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 7004
  client:
    user-service:
      address: "discovery:///user-service"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
