version: '3.3'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.1'
    container_name: 'elasticsearch'
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      discovery.type: single-node
    networks:
      - elastic
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.10.1'
    container_name: 'kibana'
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.my-organization.com
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

  logtash:
    image: 'docker.elastic.co/logstash/logstash:7.10.1'
    container_name: 'logstash'
    ports:
      - 5044:5044
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
      - ./logstash-config:/usr/share/logstash/config
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/postgres_to_elasticsearch.conf
    networks:
      - elastic

networks:
  elastic: