server:
  port: 6002

spring:

  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5002/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 7002
